[package]
name = "home-phone"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

# Using a workspace layout to make it easier
# to get integration tests working
[workspace]
members = [
  "lib",
]

[dependencies.lib]
path = "lib"

[dependencies.raspi3_boot]
git = "https://github.com/jonlamb-gh/rpi4-rust-workspace.git"
branch = "master"
default-features = false
features = []

[dependencies.log]
#version = "0.4"
git = "https://github.com/jonlamb-gh/log.git"
branch = "broken-cas"
default-features = false

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp.git"
branch = "master"
default-features = false
features = [
    "proto-ipv4",
    "socket-icmp",
    "socket-udp",
    "socket-tcp",
    "log",
    "verbose"
]

[dev-dependencies.test-runner]
path = "deps/test-runner"

[dev-dependencies.qemu]
path = "deps/qemu"

[package.metadata.cargo-xbuild]
sysroot_path = "target/sysroot"
