[package]
name = "home-phone"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies.bcm2711-hal]
git = "https://github.com/jonlamb-gh/rpi4-rust-workspace.git"
branch = "master"

[dependencies.raspi3_boot]
git = "https://github.com/jonlamb-gh/rpi4-rust-workspace.git"
branch = "master"
default-features = false
features = ["panic-uart1"]
