[package]
name = "raspi4-boot"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
cortex-a = "2.7"
r0 = "0.2"

[features]
default = ["uboot-loadaddr"]
bare-metal-loadaddr = []
uboot-loadaddr = []
