[package]
name = "qemu"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies.log]
#version = "0.4"
git = "https://github.com/jonlamb-gh/log.git"
branch = "broken-cas"
default-features = false
